### PR TITLE
Iss#91 iss#95 community admin repository not storing unique admins and postman data for easier testing

### LINKED ISSUE #91: CommunityAdminRepository not storing unique admins
## 🐛 Describe the bug

Added a method to CommunityAdminRepisitory to findAdminById but when used, an exception is thrown saying multiple results are returned where only one is expected. This is because it appears that multiple community admins with the same ID are being added to the repository

## ⚠️ Current behavior

When adding a community admin to a community, the community controller takes the admin list and adds it to the community's admin list. It then saves the community admin to CommunityAdminRepository. However when the community is being saved also, this set of admins is being saved, which appears to be why admins are getting duplicated in the repository

## ✅ Expected behavior

When findByAdminId is called it should return 1 community admin or nothing if not found.

Each row in the community repository should be unique and not duplicated

## 💣 Steps to reproduce

- Add a findByAdminId to the CommunityAdminRepository which takes the parameter String adminId
- Somewhere in a controller method that takes an admin id, call the findByAdminId method (you don't need to do anything with the result)
- Build using gradlew assemble. 
- Run the application using the jar file
- List users and choose one of the user and copy it's user id
- List communities and choose one community id to copy
- Add the user id you copied to the community admins by using the Add admin to Community request
- With the endpoint that you added the findByAdminId call to, run it and the exception should occur

## 📱 Tech info

- Device: Docker/Jar file
- OS: Ubuntu 20.04
- Library/App version: Java 8

### LINKED ISSUE #95: Load postman data for easier testing
## 🐛 Describe the bug

* `DataLoader.java` has a commented out method call `loadPostmanData()`. The intention of this method is to aid in quickly testing out a new feature.

## ⚠️ Current behavior

* This method is commented out as of now. Which makes it cumbersome to quickly test out with pre-existing data.

## ✅ Expected behavior

* `*.postman` file inside `postman` folder can be imported inside postman client. All the APIs inside that should work fine.
* Another approach is to modify the APIs inside `*.postman` file to match the IDs with the one in `data.sql` file.

## 💣 Steps to reproduce

* Start the application and execute APIs from postman client. Most of the APIs will fail.

### PR DESCRIPTION
**Pull request by DDmit04**
## 🚀 Description

* Add postman test data to `data.sql` (this changes includes [my pull request](https://github.com/jmprathab/MyHome/pull/96))
* All admins in data.sql now have a unique adminId, so a CommunityAdminRepository search for adminId will return one admin
* I done some refactor `CommunitySDJpaService` (I'm not so sure about this changes): 
  * `addAdminsToCommunity` method now not creating new admins, only add admins to community by admins ids (if admins with this ids exists) and return `Community` with added admins

  * `addHousesToCommunity` method not creating new houses, only add houses to community by houses ids (if house with this ids exists) and return Set of successfuly added houses Ids

## 📄 Motivation and Context

Closing #91 
Closing #95 

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java [hunk 1]
```diff
@@ -66,59 +68,49 @@ public CommunitySDJpaService(CommunityRepository communityRepository,
...
-    communityRepository.save(community);
-
-    Set<String> houseIds = new HashSet<>(savedHouses.size());
-    savedHouses.forEach(communityHouse -> houseIds.add(communityHouse.getHouseId()));
-    return houseIds;
+    Optional<Community> communitySearch = communityRepository.findByCommunityId(communityId);
+    return communitySearch.map(community -> {
+      Set<CommunityHouse> savedHouses = houses.stream()
+          .filter(house -> communityHouseRepository.findByHouseId(house.getHouseId()) != null)
+          .peek(house -> house.setCommunity(community))
```
Comment (jmprathab) [inline src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: Prefer map to peek. Peek is more for debugging. 

https://stackoverflow.com/questions/44370676/java-8-peek-vs-map

**Comment by DDmit04** [comment]
in this method 
```
@Override
  @Transactional
  public Integer deleteCommunity(String communityId) {

    getCommunityDetailsById(communityId).ifPresent(community -> {
      community.getHouses()
          .stream()
          .map(CommunityHouse::getHouseId)
          .forEach(communityHouseRepository::deleteByHouseId);
    });
    return communityRepository.deleteByCommunityId(communityId);
  }
```
deleting a community deletes all houses within it. Is this fine?

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java (hunk 1 above)
Comment (mslowiak) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: Yes, let's create new object to have immutability here.
Lombok has @With or @Wither annotation to simplify this

**Comment by DDmit04** [comment]
when I call DELETE (`/communities/{communityId}/houses/{houseId}`) or DELETE (`/communities/{communityId}/admins/{adminId}`) then get 403. I can't uderstand why. Someone know why this happens?

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java [hunk 2]
```diff
@@ -130,7 +133,18 @@ private String generateUniqueId() {
...
-  public void deleteHouseFromCommunityByHouseId(String houseId) {
-    communityHouseRepository.deleteByHouseId(houseId);
+  public boolean removeHouseFromCommunityByHouseId(String communityId, String houseId) {
+    return communityRepository.findByCommunityId(communityId)
+        .map(community -> {
+          CommunityHouse house = communityHouseRepository.findByHouseId(houseId);
+          if(house != null && community.getHouses().contains(house)) {
+            community.getHouses().remove(house);
+            communityRepository.save(community);
+            return true;
```
Comment (DDmit04) [inline src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java:143]: I can't make `communityHouseRepository.findByHouseId(houseId)` return `Optinal<CommunityHouse>` because this change affect on `HouseSDJpaService`. May be should create an issue for refactor `HouseSDJpaService`

**Comment by jmprathab** [comment]
> in this method
> 
> ```
> @Override
>   @Transactional
>   public Integer deleteCommunity(String communityId) {
> 
>     getCommunityDetailsById(communityId).ifPresent(community -> {
>       community.getHouses()
>           .stream()
>           .map(CommunityHouse::getHouseId)
>           .forEach(communityHouseRepository::deleteByHouseId);
>     });
>     return communityRepository.deleteByCommunityId(communityId);
>   }
> ```
> 
> deleting a community deletes all houses within it. Is this fine?

@DDmit04 Sorry for the delayed response. I was busy. This is fine and expected behaviour.
