### PR TITLE
Fixed issues identified by @mslowiak in pull request #122

### LINKED ISSUE #102: HealthCheckController unit tests
## Task description

There is a need to create unit tests for `HealthCheckController`.
As an example, you can have a look at `UserControllerTest`.

## Task Relationships
This task is a sub-task of: #100

### PR DESCRIPTION
**Pull request by edwardUL99**
## 🚀 Description

Made HealthCheckController.statusCheck return a ResponseEntity<String>

Added given when then pattern to the unit test

## 📄 Motivation and Context

@mslowiak raised review comments regarding these changes in PR #122 
These were made after it was merged, so have to create a new PR to resolve it

## 🧪 How Has This Been Tested?

./gradlew build

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/test/java/com/myhome/controllers/unit/HealthCheckControllerTest.java [hunk 1]
```diff
@@ -5,21 +5,31 @@
...
   }
 
   @Test
   void shouldReturnHealthySuccessfully() {
-    assertEquals("Application is healthy", healthCheckController.statusCheck());
+    // given
+    String healthyMessage = "Application is healthy";
+
+    // when
+    ResponseEntity<String> responseEntity =
```
Comment (mslowiak) [inline src/test/java/com/myhome/controllers/unit/HealthCheckControllerTest.java]: Is this line break needed? I think it can be one line

File: src/test/java/com/myhome/controllers/unit/HealthCheckControllerTest.java [hunk 2]
```diff
@@ -5,21 +5,31 @@
...
+import org.springframework.http.ResponseEntity;
 
 import static org.junit.jupiter.api.Assertions.assertEquals;
 
 public class HealthCheckControllerTest {
 
   @InjectMocks
-  HealthCheckController healthCheckController;
-
+  private HealthCheckController healthCheckController;
```
Comment (mslowiak) [inline src/test/java/com/myhome/controllers/unit/HealthCheckControllerTest.java:16]: Can we add one blank line after `healthCheckController` ?

**Review by mslowiak — APPROVED** [review]
