### PR TITLE
Issue #149 : Add current user as Admin when creating a community

### LINKED ISSUE #149: Add current user as Admin when creating a community
## 🐛 Describe the bug

* When creating a new community using `POST /communities` current user should be added as the Admin of the community

## ⚠️ Current behavior

* Admin list of newly created community is empty

## ✅ Expected behavior

* User who creates the community should be an admin of it - Verify this using `GET /communities/:communityId/admins`

## 💣 Steps to reproduce

* `POST /communities`

## 📱 Tech info

- Device: Not applicable
- OS: All
- Library/App version: latest master

### PR DESCRIPTION
**Pull request by tomsajuk**
## 🚀 Description

Adding the current user as Admin when creating a community. The userId is taken from the SecurityContextHolder.

## 📄 Motivation and Context

Change is required as there are no admins being assigned to a newly created community.
Fixes [Issue #149 ](https://github.com/jmprathab/MyHome/issues/149)

## 🧪 How Has This Been Tested?

Tested using Postman and Testcases.

## 📷 Screenshots (if appropriate)
NA

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: service/src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java [hunk 1]
```diff
@@ -52,7 +53,14 @@
   @Override
   public Community createCommunity(CommunityDto communityDto) {
     communityDto.setCommunityId(generateUniqueId());
+    String userId = (String) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
     Community community = communityMapper.communityDtoToCommunity(communityDto);
+    communityAdminRepository.findByUserIdWithCommunities(userId).ifPresent(admin -> {
+      admin.getCommunities().add(community);
```
Comment (mslowiak) [inline service/src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java:66]: Let's extract that action to a separate method please :)

**Review by mslowiak — CHANGES_REQUESTED** [review]

**Comment by mslowiak** [comment]
If you could also rename the commit message "Made changes to the test case" to "Issue 149: Made changes to the test case" I would be grateful. Thanks!

**Comment by tomsajuk** [comment]
@mslowiak Made a fresh start with a single commit. Hope that's okay

**Review by mslowiak — APPROVED** [review]

**Comment by mslowiak** [comment]
@tomsajuk great, thanks!
