### PR TITLE
Issue #150: Allow only existing admins to add admins to a community

### LINKED ISSUE #150: Allow only existing admins to add admins to a community
## 🐛 Describe the bug

*`POST /communities/:communityId/admins` should be only restricted to existing admins of the community 
* Note: Can be only picked up after #149

## ⚠️ Current behavior

* Anyone can now call `POST /communities/:communityId/admins`

## ✅ Expected behavior

* Restrict `POST /communities/:communityId/admins` only to existing admins

## 💣 Steps to reproduce

* `POST /communities/:communityId/admins` on a newly created community

## 📱 Tech info

- Device: Not applicable
- OS: All
- Library/App version: latest master

### PR DESCRIPTION
**Pull request by WOLFI3654**
## 🚀 Description
POST /communities/{communityId}/admins now requires
The current user to be administrator.

Implements #150

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mslowiak** [comment]
@WOLFI3654 Please take a look on our contributing guide and apply naming convention to the commit names please.
https://github.com/jmprathab/MyHome/blob/master/CONTRIBUTING.md

**Comment by WOLFI3654** [comment]
I dont know if this worked as expected. I installed the Square.xml and hit format. Either the Style was not correct or the whole file was not formatted correctly.

**Comment by mslowiak** [comment]
Styling looks good, you need now to rename your commits:
`Add Admin Check` -> `Issue #150: Add Admin Check`
`Apply CodeStyle Square.xml` -> `Issue #150: Apply CodeStyle Square.xml`

**Comment by jmprathab** [comment]
@WOLFI3654 Thanks for the changes. Just a note for the future - try to use Github keyword for referencing issues in your PR description.

https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

File: service/src/main/java/com/myhome/controllers/CommunityController.java [hunk 1]
```diff
@@ -194,6 +195,15 @@
       @PathVariable String communityId, @Valid @RequestBody
       AddCommunityAdminRequest request) {
     log.trace("Received request to add admin to community with id[{}]", communityId);
+    String userId = (String) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
```
Comment (jmprathab) [inline service/src/main/java/com/myhome/controllers/CommunityController.java]: @WOLFI3654 The idiomatic way of doing this in Spring is to add an AuthorizationFilter to the chain. 
Can you make the changes to add an AuthorizationFilter instead of adding the logic here? BTW, please do not forget to add test cases for your changes.

Please refer to jmprathab/MyHome/pull/165 for reference implementation if required.

**Review by jmprathab — CHANGES_REQUESTED** [review]

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -24,3 +28,20 @@ Please note we have a [code of conduct](CODE_OF_CONDUCT.md), please follow it in
 ## How to set up your environment and run tests?
 
 1. Building and installation instructions are present in README.md file.
+
+## Coding Style
```
Comment (jmprathab) [inline CONTRIBUTING.md:32]: Thanks for this 😊
This was long pending due. It would have been excellent if it was changed in another PR. But, it is absolutely fine for now😊

**Comment by mslowiak** [comment]
@WOLFI3654 I think you messed little bit with commits (I see contribute.md file committed). Would be great to fix that. If you don't know how, reach me out on discord I will show you how to use cherry-pick and other things.

**Comment by WOLFI3654** [comment]
Oh sorry. I thought that "implements" was a git keyword aswell

**Review by jmprathab — APPROVED** [review]
Looks good
