### PR TITLE
Issue 140: CommunitySDJpaServiceTest deleteCommunity fails

### LINKED ISSUE #140: CommunitySDJpaServiceTest deleteCommunity fails
## 🐛 Describe the bug

deleteCommunity fails with the following error:
Wanted 1 time:
-> at com.myhome.services.unit.CommunitySDJpaServiceTest.deleteCommunity(CommunitySDJpaServiceTest.java:346)
But was 3 times:
-> at com.myhome.services.springdatajpa.CommunitySDJpaService.deleteCommunity(CommunitySDJpaService.java:173)
-> at com.myhome.services.springdatajpa.CommunitySDJpaService.removeHouseFromCommunityByHouseId(CommunitySDJpaService.java:195)
-> at com.myhome.services.springdatajpa.CommunitySDJpaService.removeHouseFromCommunityByHouseId(CommunitySDJpaService.java:195)

## ⚠️ Current behavior
deleteCommunity() test fails

## ✅ Expected behavior

deleteCommunity should pass if the code is correct, but fails everytime

## 💣 Steps to reproduce

Run the CommunitySDJpaService test

## 📱 Tech info

- Device: Junit
- OS: All
- Library/App version: Java8

### PR DESCRIPTION
**Pull request by edwardUL99**
## 🚀 Description

Had to fix the deleteCommunity test as there were no calls to given...wil return for find by house ID for each test house and also verify wasn't set up correctly for verify(communityRepository).findByCommunityId was not setup correctly(had to add times(3)) as it is called 3 times in CommunitySDJpaService

## 📄 Motivation and Context

Closes #140 

## 🧪 How Has This Been Tested?

Ran the unit tests 

## 📦 Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [X] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java [hunk 1]
```diff
@@ -337,13 +338,17 @@ void deleteCommunity() {
...
+        .willReturn(house);
+    });
 
     // when
     boolean communityDeleted = communitySDJpaService.deleteCommunity(TEST_COMMUNITY_ID);
 
     // then
     assertTrue(communityDeleted);
-    verify(communityRepository).findByCommunityId(TEST_COMMUNITY_ID);
+    verify(communityRepository, times(3)).findByCommunityId(TEST_COMMUNITY_ID);
```
Comment (mslowiak) [inline src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java]: I guess community should be passed to `removeHouseFromCommunityByHouseId` method instead of just id since we dont want to make `findByCommunityId` twice for same Id

Comment (edwardUL99) [reply src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java]: Ya I was thinking that. This would require a change to code that calls that method too to pass the Community in. Or else we could have a private method and the public facing method with community id then just calls that private method. Our delete community method could then call the private one?

Comment (mslowiak) [reply src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java]: Let's just switch the method arguments from:
`removeHouseFromCommunityByHouseId(String communityId, String houseId)`

to:

`removeHouseFromCommunityByHouseId(Community community, String houseId)`

that should not be a big effort to change that but will do significant code adjustment

Comment (edwardUL99) [reply src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java]: It will need to refactor the community unit test and possible other code if we use that approach rather than a public facing function with the ID. But I can do that

**Comment by edwardUL99** [comment]
I accidentally made my changes on the refactoring_payment_fields branch so had to rebase this branch, hence why it says 20 files changed
