### PR TITLE
Issue:121: Adding CommunityAdmin to community doesn't actually add them 

### LINKED ISSUE #121: Adding CommunityAdmin to community doesn't actually add them
## 🐛 Describe the bug

When using Postman to add a user id to a community as an admin, in the response body, the added user id does not show up. I debugged the code and found it was not added in the community's admin set either. I am unclear of what Add community admin is supposed to do since, we can't seem to create a community admin, I assumed it was just add a user id

## ⚠️ Current behavior

When I add a user id to the request body for adding an admin to a specified community, the response body does not contain this user id so it was not successfully added

## ✅ Expected behavior

When a user id is added to the community as an admin, the user id should show up in the response body and also in the list of community admins request

## 💣 Steps to reproduce

- Run the create user endpoint and login, obtaining the bearer token to use for the following requests
- List all users and choose one to be admin and copy their user id
- List all communities and choose a community id to use in a add admin to community request
- Using this community id, in the add admin request body, paste the user id you obtained
- Submit the request and you'll see in the response body, the id does not appear. 
- Submit a list all admins for that community request and it does not appear also

I believe the issue is in this code:
 
    return communitySearch.map(community -> {
      adminsIds.forEach(adminId -> {
        communityAdminRepository.findByAdminId(adminId).map(admin -> {
          admin.getCommunities().add(community);
          community.getAdmins().add(communityAdminRepository.save(admin));
          return admin;
        });
      });
      return Optional.of(communityRepository.save(community));
    }).orElseGet(Optional::empty);

This is in the addAdminsToCommunity method of CommunitySDJPAService starting at line 98

In the forEach loop of adminIds (the set of admin ids being added), you are using the community admin repository to find an admin using this id. This admin is then saved in the community.getAdmins().add(communityAdminRepository.save(admin));  But this code is never reached since if this adminId is new and was not added to the community as an admin before it wouldn't have been saved, and hence findByAdminId would return an empty Optional object, and the map function never being called. Because of this, new admins are never added.

I can take a look at fixing this but need clarification on exactly who can be a community admin, i.e. is it just a user where their user id is added as the admin or is an admin separate to a user and needs to be created? Just thought I'd log the bug report and go from there.

## 📱 Tech info

- Device: Docker 
- OS: Ubuntu
- Library/App version: Java 8

### PR DESCRIPTION
**Pull request by edwardUL99**
## 🚀 Description

Fixed an issue where when you attempted to add a community admin to a community, they would not be added. This required merging User and CommunityAdmin classes and when done removed the CommunityAdmin class.

This functionality now works correctly.

Also added functionality when scheduling a payment to check if the Admin is in fact an admin of the community that house member is transitively a part of by the House they are a member of. i.e. community A has house B and member C. C is a member of A through B.

Testing this I found an issue where houses could not be added to a community. This has been fixed now however

Also fixed a bug where when listing all users, the community Ids showed null

## 📄 Motivation and Context

This closes #121 
Admins could not be added to communities successfully

## 🧪 How Has This Been Tested?

I have tested this using all the unit tests. I called them using gradlew build

Also used Postman to add a sample user to a community as an admin, add a user to a house as a house member, added this house to the community and then scheduled a payment using the admin and member Ids

These worked successfully. I verified by listing all houses of the community, and the added house appeared

I tested the case where an admin wasn't a part of the community the house member was in and that gave the expected result

## 📦 Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [X] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java [hunk 1]
```diff
@@ -41,7 +41,8 @@
 @Service
 public class CommunitySDJpaService implements CommunityService {
   private final CommunityRepository communityRepository;
-  private final CommunityAdminRepository communityAdminRepository;
+  //private final CommunityAdminRepository communityAdminRepository;
```
Comment (jmprathab) [inline src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: Let's remove this if not required.

File: src/main/resources/application.yml [hunk 2]
```diff
@@ -21,6 +21,18 @@ server:
...
+  level:
+    org:
+      hibernate:
+        SQL: DEBUG
+        type:
+          descriptor:
+            sql:
+              BasicBinder: TRACE
+        
+
```
Comment (jmprathab) [inline src/main/resources/application.yml]: This can be removed.

**Comment by edwardUL99** [comment]
Sorry for all the commits, was trying to rebase and ran into a lot of issues so just had to commit them all separate

File: src/main/java/com/myhome/bootstrap/DataLoader.java [hunk 3]
```diff
@@ -36,7 +34,8 @@
 @RequiredArgsConstructor
 class DataLoader implements CommandLineRunner {
   private final CommunityRepository communityRepository;
-  private final CommunityAdminRepository communityAdminRepository;
+  //private final CommunityAdminRepository communityAdminRepository;
```
Comment (mslowiak) [inline src/main/java/com/myhome/bootstrap/DataLoader.java]: Why is it in the comments?

File: src/main/java/com/myhome/bootstrap/DataLoader.java [hunk 4]
```diff
@@ -98,17 +97,17 @@ private CommunityHouse addCommunityHouse(Community savedCommunity) {
...
     savedCommunity.getAdmins().add(savedCommunityAdmin);
     return communityRepository.save(savedCommunity);
   }
 
-  private CommunityAdmin saveCommunityAdmin(Community savedCommunity) {
-    CommunityAdmin communityAdmin = new CommunityAdmin();
-    communityAdmin.setAdminId(TestDataConstants.ADMIN_ID);
+  private User saveCommunityAdmin(Community savedCommunity) {
+    User communityAdmin = new User();
+    communityAdmin.setUserId(TestDataConstants.ADMIN_ID);
```
Comment (mslowiak) [inline src/main/java/com/myhome/bootstrap/DataLoader.java]: Let's use `@With` annotation from lombok instead of this approach

File: src/main/java/com/myhome/controllers/mapper/UserApiMapper.java [hunk 5]
```diff
@@ -38,4 +44,15 @@
   CreateUserResponse userDtoToCreateUserResponse(UserDto userDto);
 
   GetUserDetailsResponse.User userDtoToGetUserDetailsResponse(UserDto userDto);
+
+  @Mapping(source = "communities", target = "communityIds", qualifiedByName = "communitySetToIdsSet")
+  GetUserDetailsResponse.User userToRestApiUser(User user);
+
+  @Named("communitySetToIdsSet")
+  static Set<String> communityObjectSetToCommunityIdSet(Set<Community> communities) {
+    return communities
```
Comment (mslowiak) [inline src/main/java/com/myhome/controllers/mapper/UserApiMapper.java]: Let's move `.stream()` in the same line like `communities`:
`communities.stream()`

File: src/main/java/com/myhome/domain/CommunityHouse.java [hunk 6]
```diff
@@ -35,10 +34,10 @@
 @NoArgsConstructor
 @Getter
 @Setter
-@EqualsAndHashCode(exclude = "community", callSuper = false)
+//@EqualsAndHashCode(exclude = "community", callSuper = false)
```
Comment (mslowiak) [inline src/main/java/com/myhome/domain/CommunityHouse.java]: commented code

File: src/main/java/com/myhome/domain/CommunityHouse.java [hunk 7]
```diff
@@ -47,4 +46,20 @@
   private String houseId;
   @OneToMany(fetch = FetchType.EAGER)
   private Set<HouseMember> houseMembers = new HashSet<>();
+  @Override
+  public boolean equals(Object obj) {
```
Comment (mslowiak) [inline src/main/java/com/myhome/domain/CommunityHouse.java]: Why this is needed instead of lombok one?

File: src/main/java/com/myhome/controllers/PaymentController.java [hunk 8]
```diff
@@ -59,9 +62,26 @@
...
-        .map(requestPaymentDto -> schedulePaymentApiMapper.schedulePaymentRequestToPaymentDto(
-            request))
+        .map(houseMember -> {
+          boolean adminExists = communityService.findCommunityAdminById(adminId)
+            .map(admin -> {
+              CommunityHouse house = houseMember.getCommunityHouse();
+              Community community = house.getCommunity();
+              return community.getAdmins()
+                .stream()
+                .anyMatch(admin1 -> admin.getUserId().equals(adminId)); //makes sure this user is an admin of the community this member belongs to
```
Comment (mslowiak) [inline src/main/java/com/myhome/controllers/PaymentController.java]: Why we need to make a such filtering?
`findCommunityAdminById` should give us that information - so the `CommunitySDJpaService::findCommunityAdminById` should call appropriate repository method to fetch those data on database side. @jmprathab what do you think there?

Also this `map` operation looks so big and awful. We should use `.filter()` for filtering the data as a separate step.

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java [hunk 9]
```diff
@@ -113,29 +118,45 @@ public Community createCommunity(CommunityDto communityDto) {
...
+        house = communityHouseRepository.findByHouseId(house.getHouseId());
+
+        if (house != null) {
+          Community houseCommunity = house.getCommunity();
+
+          if (houseCommunity != null) {
+            CommunityHouse finalHouse = house;
+            communityRepository.findByCommunityId(houseCommunity.getCommunityId())
+              .map(community1 -> {
+                community1.getHouses().remove(finalHouse);
```
Comment (mslowiak) [inline src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: Why we delete here a house? I don't get this logic

File: src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java [hunk 10]
```diff
@@ -68,24 +67,22 @@
...
-          .filter(community -> community.getAdmins()
-              .stream()
-              .map(CommunityAdmin::getAdminId)
-              .collect(Collectors.toSet())
-              .contains(userId)
-          )
-          .map(Community::getCommunityId)
-          .collect(Collectors.toSet());
+      .filter(community -> community.getAdmins()
+      .stream()
```
Comment (mslowiak) [inline src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java]: formatting

**Review by mslowiak — CHANGES_REQUESTED** [review]

**Comment by mslowiak** [comment]
We have updated the contributing guide with points 5 and 6.
Please take a look and apply the required changes:
[contributing.md](https://github.com/jmprathab/MyHome/blob/master/CONTRIBUTING.md)

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java (hunk 9 above)
Comment (edwardUL99) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: Because if you don't remove it, when adding a house to a community it would cause a SQL error if that house was added to a different community before since it would violate a unique key constraint so you need to remove it from the old community before adding it to the new one

**Comment by edwardUL99** [comment]
I had all those comments and unnecessary equals methods removed. They must have been added back in when I was trying to rebase it, my apologies 🤦‍♂️ I'll sort it out tonight

File: src/main/java/com/myhome/controllers/PaymentController.java (hunk 8 above)
Comment (edwardUL99) [reply src/main/java/com/myhome/controllers/PaymentController.java]: I'll look into that. I don't see the map function you are talking about in the code you commented on but I think 8 know what you're talking about. To fix the issue with not being able to add houses, it was not possible with a small map operation as there were too many steps to break it up into more optional. I found using s loop to be much nearer here but tried my best to keep it using a map. I'll see if I can shorten it down but that was after multiple attempts to get it working while not using a for loop

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java (hunk 9 above)
Comment (mslowiak) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: @jmprathab Can you explain that logic? I mean it is strange to delete house from one community and add it to another in addHouse method.

File: src/main/java/com/myhome/controllers/PaymentController.java (hunk 8 above)
Comment (mslowiak) [reply src/main/java/com/myhome/controllers/PaymentController.java]: Even using a simple method to group that content of map is better than creating a one big multiline map operation.

Here you could make a method to check if it is admin and use it in `.filter()` operator. then you could call `.map()` with `schedulePaymentApiMapper.schedulePaymentRequestToPaymentDto(request)` logic.

However, let's try to fix it in the way that I mentioned in first comment

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java (hunk 9 above)
Comment (edwardUL99) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: A house can't be in 2 communities at once so that's why it needs to be removed from another if it was already in a community before it wants to be added to the new community or else it means you'll violate the unique key for house id trying to add it to a second community.

But I suppose we could remove logic removing the house in the add house method and call a method that removes the house from the old community

Comment (mslowiak) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: Yes, I understand the code problem but the domain problem seems to be strange.

How we can know that such person can 'disconnect' and 'connect' house between communities?
Maybe I miss something.

Comment (edwardUL99) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: I get what you mean. Wouldn't imagine somebody can move a house from community to community! I just found there's no code to add a new house to a new community. All the houses in the system at runtime have already been loaded in and they all seem to have communities already when retrieved from the repository hence why I added that code. So I'm not sure how to resolve this. As when adding a house to a community, the code checks if that house exists first before adding it, so it had to be added before hand before it can be added to a community! So you can't create a new house here. @jmprathab what are your thoughts?

Comment (jmprathab) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: > @jmprathab Can you explain that logic? I mean it is strange to delete house from one community and add it to another in addHouse method.

Yeah, this is not the business use case. We should never let a house to be moved/added to another community. Having said that, there can be two houses in two different communities with the same name and name of the house within a community has to be unique.

Comment (jmprathab) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: > I get what you mean. Wouldn't imagine somebody can move a house from community to community! I just found there's no code to add a new house to a new community. All the houses in the system at runtime have already been loaded in and they all seem to have communities already when retrieved from the repository hence why I added that code. So I'm not sure how to resolve this. As when adding a house to a community, the code checks if that house exists first before adding it, so it had to be added before hand before it can be added to a community! So you can't create a new house here. @jmprathab what are your thoughts?

I believe the implementation has to be something like this.
1. Do a single pass to check if the houses we are going to add is already part of the community(Check for name uniqueness). If a house with the same name exists, we should just return an error from the API without proceeding.
2. Persist all the community houses.
3. Update community entity to add all the newly persisted house and persist community.

So, this API needs a bit of refactoring. We should never get House Id from the user to add it. The only data this API needs to take is a list of house names.

Comment (jmprathab) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java:135]: So, this API needs a bit of refactoring. We should never get House Id from the user to add it. The only data this API needs to take is a list of house names.

Comment (mslowiak) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: > > I get what you mean. Wouldn't imagine somebody can move a house from community to community! I just found there's no code to add a new house to a new community. All the houses in the system at runtime have already been loaded in and they all seem to have communities already when retrieved from the repository hence why I added that code. So I'm not sure how to resolve this. As when adding a house to a community, the code checks if that house exists first before adding it, so it had to be added before hand before it can be added to a community! So you can't create a new house here. @jmprathab what are your thoughts?
> 
> I believe the implementation has to be something like this.
> 
> 1. Do a single pass to check if the houses we are going to add is already part of the community(Check for name uniqueness). If a house with the same name exists, we should just return an error from the API without proceeding.
> 2. Persist all the community houses.
> 3. Update community entity to add all the newly persisted house and persist community.
> 
> So, this API needs a bit of refactoring. We should never get House Id from the user to add it. The only data this API needs to take is a list of house names.

That's right! :-)

Comment (edwardUL99) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: > > @jmprathab Can you explain that logic? I mean it is strange to delete house from one community and add it to another in addHouse method.
> 
> Yeah, this is not the business use case. We should never let a house to be moved/added to another community. Having said that, there can be two houses in two different communities with the same name and name of the house within a community has to be unique.

The issue with this though is that you will get that SQL Unique Key violation error. We'll have to see if there's another way to fix that

File: src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java (hunk 10 above)
Comment (edwardUL99) [reply src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java]: I don't understand what needs to be changed here

Comment (mslowiak) [reply src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java]: There is a nested stream into first one.
It should be tabbed out like in previous implementation (right now all lines starts with same line starting point).
Let's move also `.stream()` from line 74 to 73

File: src/main/java/com/myhome/controllers/PaymentController.java (hunk 8 above)
Comment (edwardUL99) [reply src/main/java/com/myhome/controllers/PaymentController.java:76]: The way I have it there is checking if the admin in the payment is a part of that community. AN admin got by findCommunityAdminById could be in any community no?

File: src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java (hunk 9 above)
Comment (edwardUL99) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: > > I get what you mean. Wouldn't imagine somebody can move a house from community to community! I just found there's no code to add a new house to a new community. All the houses in the system at runtime have already been loaded in and they all seem to have communities already when retrieved from the repository hence why I added that code. So I'm not sure how to resolve this. As when adding a house to a community, the code checks if that house exists first before adding it, so it had to be added before hand before it can be added to a community! So you can't create a new house here. @jmprathab what are your thoughts?
> 
> I believe the implementation has to be something like this.
> 
>     1. Do a single pass to check if the houses we are going to add is already part of the community(Check for name uniqueness). If a house with the same name exists, we should just return an error from the API without proceeding.
> 
>     2. Persist all the community houses.
> 
>     3. Update community entity to add all the newly persisted house and persist community.
> 
> 
> So, this API needs a bit of refactoring. We should never get House Id from the user to add it. The only data this API needs to take is a list of house names.

So when you take this list of house names @jmprathab, it's supposed to create a new house entity with a new random id? Or how do you want to approach it?

Comment (jmprathab) [reply src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java]: > So when you take this list of house names @jmprathab, it's supposed to create a new house entity with a new random id? Or how do you want to approach it?

@edwardUL99 That's right. It should create a new `CommunityHouse` with a random UUID and add it to the `Community`

**Comment by edwardUL99** [comment]
@jmprathab @mslowiak Is this ok to merge? I won't be able to fix anything if it's not om till Monday

**Comment by jmprathab** [comment]
> @jmprathab @mslowiak Is this ok to merge? I won't be able to fix anything if it's not om till Monday

I was waiting for @mslowiak to approve.

**Review by mslowiak — APPROVED** [review]

**Comment by mslowiak** [comment]
Sorry for delay guys :)
